{#
  This macro is auto-generated by the DBT Core MCP Server.
  Version: 1.0.1
  
  Purpose: Execute arbitrary SQL queries without automatic LIMIT clauses.
  Used by: The query_database MCP tool via dbt run-operation.
  
  You can safely delete this file if you're not using the MCP server,
  or you can use it directly with: dbt run-operation __mcp_execute_sql --args '{sql: "..."}'
#}

{% macro __mcp_execute_sql(sql) %}
    {% set results = run_query(sql) %}
    {% if execute %}
        {{ log('__MCP_QUERY_RESULTS_START__', info=true) }}
        {{ results.print_json() }}
        {{ log('__MCP_QUERY_RESULTS_END__', info=true) }}
    {% endif %}
{% endmacro %}
